apiVersion: v2
appVersion: 1.36.0
description: Bridges events and allows you to control your Zigbee devices via MQTT
name: zigbee2mqtt
version: 1.36.0+chart5
kubeVersion: ">=1.16.0-0"
keywords:
  - zigbee
  - mqtt
  - home-assistant
home: https://github.com/jlpedrosa/zigbee2mqtt-charts
icon: https://www.zigbee2mqtt.io/logo.png
sources:
  - https://github.com/Koenkk/zigbee2mqtt
  - https://github.com/jlpedrosa/zigbee2mqtt-charts
maintainers:
  - name: Jose Luis Pedrosa
    email: jlpedrosa@gmail.com
