nameOverride: "custom-name"
fullnameOverride: "long-custom-name"

image:
  # -- Image repository for the `zigbee2mqtt` container.
  repository: koenkk/zigbee2mqtt
  tag: 1.36.0
  pullPolicy: IfNotPresent
  imagePullSecrets: { }

service:
  type: LoadBalancer
  port: 8080

statefulset:
  storage:
    storageClassName: nfs-csi
  dnsPolicy: ClusterFirst
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 100m
  tolerations: {}

zigbee2mqtt:
  homeassistant: true
  permit_join: true
  timezone: UTC
  frontend:
    url: http://0.0.0.0:8080
  mqtt:
    base_topic: zigbee2mqtt
    server: mqtt://mosquitto
    user: "test"
    password: "test"
  serial:
    port: tcp://10.50.30.200:6638
    baudrate: 115200
    adapter: ezsp
    disable_led: false
  advanced:
    transmit_power: 20
    log_level: debug




