apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{ include "zigbee2mqtt.labels" . | indent 2 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  configuration.yaml: |
    # Define the files which contains the configs. As k8s config maps
    # Are read only by design, we need to extract dynamic config to external files
    devices: devices.yaml
    groups: groups.yaml

    homeassistant: {{ .Values.zigbee2mqtt.homeassistant }}
    permit_join: {{ .Values.zigbee2mqtt.permit_join }}
    frontend:
     url: {{ .Values.zigbee2mqtt.frontend.url }}
    mqtt:
      # MQTT base topic for zigbee2mqtt MQTT messages
      base_topic: {{ .Values.zigbee2mqtt.mqtt.base_topic }}
      # MQTT server URL
      server: {{ .Values.zigbee2mqtt.mqtt.server }}
      # MQTT server authentication, uncomment if required:
      user: {{ .Values.zigbee2mqtt.mqtt.user }}
      password: {{ .Values.zigbee2mqtt.mqtt.password }}
    serial:
      port: {{ .Values.zigbee2mqtt.serial.port }}
      baudrate: {{ .Values.zigbee2mqtt.serial.baudrate }}
      adapter: {{ .Values.zigbee2mqtt.serial.adapter }}
      disable_led: {{ .Values.zigbee2mqtt.serial.disable_led }}
    advanced:
      transmit_power: {{ .Values.zigbee2mqtt.advanced.transmit_power }}
      # Optional: Logging level, options: debug, info, warn, error (default: info)
      log_level: {{ .Values.zigbee2mqtt.advanced.log_level }}
      # Optional: log timestamp format (default: shown below)
      timestamp_format: 'YYYY-MM-DD HH:mm:ss'
      # Optional: Output location of the log (default: shown below), leave empty to suppress logging (log_output: [])
      # possible options: 'console', 'file', 'syslog'
      log_output:
        - console
