apiVersion: v1
entries:
  zigbee2mqtt:
  - apiVersion: v2
    appVersion: 1.36.0
    created: "2024-03-16T21:11:39.971481037Z"
    description: Bridges events and allows you to control your Zigbee devices via
      MQTT
    digest: fccbd14b595300cbad66e4110ced419d2f44657eb9a6713217df9092e65fd899
    home: https://github.com/jlpedrosa/zigbee2mqtt-charts
    icon: https://www.zigbee2mqtt.io/logo.png
    keywords:
    - zigbee
    - mqtt
    - home-assistant
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: jlpedrosa@gmail.com
      name: Jose Luis Pedrosa
    name: zigbee2mqtt
    sources:
    - https://github.com/Koenkk/zigbee2mqtt
    - https://github.com/jlpedrosa/zigbee2mqtt-charts
    urls:
    - https://jlpedrosa.github.io/zigbee2mqtt-chart/zigbee2mqtt-1.36.0.tgz
    version: 1.36.0
generated: "2024-03-16T21:11:39.970983168Z"
